# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  USE_HARD_LINKS: false

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm install
    - run: npm run build --if-present
    - name: Upload Build Artifact ${{ matrix.os }}
      uses: actions/upload-artifact@v2
      with:
        name: artifact ${{ matrix.os }}
        path: |
          dist/electron/Packaged/*.AppImage
          dist/electron/Packaged/*.exe
        if-no-files-found: error
